apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "service.fullname" .}}
  labels:
    {{- include "service.labels" . | nindent 4}}
spec:
  {{- if not .Values.autoscaling.enabled}}
  replicas: {{.Values.replicaCount}}
  {{- end}}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6}}
  template:
    metadata:
      {{- with .Values.podAnnotations}}
      annotations:
        {{- toYaml . | nindent 8}}
      {{- end}}
      labels:
        {{- include "service.selectorLabels" . | nindent 8}}
    spec:
      {{- with .Values.imagePullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8}}
      {{- end}}
      serviceAccountName: {{include "service.serviceAccountName" .}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8}}
      containers:
        - name: {{.Chart.Name}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12}}
          image: "{{ .Values.image.imagePath }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          env:
            {{- include "service.listEnvVariables" . | nindent 12}}
          ports:
            - name: grpc
              containerPort: {{.Values.container.port}}
              protocol: TCP
          livenessProbe:
            grpc:
              port: {{.Values.container.liveness.port}}
            failureThreshold: {{.Values.container.liveness.failureThreshold}}
            periodSeconds: {{.Values.container.liveness.periodSeconds}}
          readinessProbe:
            grpc:
              port: {{.Values.container.readiness.port}}
            failureThreshold: {{.Values.container.readiness.failureThreshold}}
            periodSeconds: {{.Values.container.readiness.periodSeconds}}
          startupProbe:
            grpc:
              port: {{.Values.container.startup.port}}
            failureThreshold: {{.Values.container.startup.failureThreshold}}
            periodSeconds: {{.Values.container.startup.periodSeconds}}
          resources:
            {{- toYaml .Values.resources | nindent 12}}
      {{- with .Values.nodeSelector}}
      nodeSelector:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.affinity}}
      affinity:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.tolerations}}
      tolerations:
        {{- toYaml . | nindent 8}}
      {{- end}}
